sonar.projectKey=lab3-project
sonar.working.directory=C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth
sonar.pullrequest.cache.basepath=C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth

60C9B63B-A37A-4AB1-940E-890FAEF7541D.sonar.projectKey=lab3-project:60C9B63B-A37A-4AB1-940E-890FAEF7541D
60C9B63B-A37A-4AB1-940E-890FAEF7541D.sonar.projectName=Lab3.Auth
60C9B63B-A37A-4AB1-940E-890FAEF7541D.sonar.projectBaseDir=C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth
60C9B63B-A37A-4AB1-940E-890FAEF7541D.sonar.sourceEncoding=utf-8
60C9B63B-A37A-4AB1-940E-890FAEF7541D.sonar.tests=
60C9B63B-A37A-4AB1-940E-890FAEF7541D.sonar.sources=\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\Controllers\\AuthController.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\Program.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\Services\\AuthService.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\Lab3.Auth.GlobalUsings.g.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\Lab3.Auth.AssemblyInfo.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\appsettings.Development.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\appsettings.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\Lab3.Auth.http",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\Properties\\launchSettings.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Lab3.Auth.csproj.nuget.dgspec.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\project.assets.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\bin\\Debug\\net10.0\\Lab3.Auth.deps.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\bin\\Debug\\net10.0\\Lab3.Auth.runtimeconfig.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\bin\\Debug\\net10.0\\Lab3.Auth.staticwebassets.endpoints.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\staticwebassets.build.json"

60C9B63B-A37A-4AB1-940E-890FAEF7541D.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\.sonarqube\\out\\0"
60C9B63B-A37A-4AB1-940E-890FAEF7541D.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\.sonarqube\\out\\0\\Issues.json"
60C9B63B-A37A-4AB1-940E-890FAEF7541D.sonar.cs.scanner.telemetry=\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\.sonarqube\\out\\0\\Telemetry.json"

60C9B63B-A37A-4AB1-940E-890FAEF7541D.sonar.working.directory=C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=60C9B63B-A37A-4AB1-940E-890FAEF7541D

