sonar.projectKey=lab3-project
sonar.working.directory=C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\Tujh\\Desktop\\LR3pidis
sonar.pullrequest.cache.basepath=C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests
sonar.sources=\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\.github\\workflows\\ci.yml",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\sonar-project.properties"

84BF7BC8-19C7-4DF1-8220-0688EC133324.sonar.projectKey=lab3-project:84BF7BC8-19C7-4DF1-8220-0688EC133324
84BF7BC8-19C7-4DF1-8220-0688EC133324.sonar.projectName=Lab3.Auth
84BF7BC8-19C7-4DF1-8220-0688EC133324.sonar.projectBaseDir=C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth
84BF7BC8-19C7-4DF1-8220-0688EC133324.sonar.sourceEncoding=utf-8
84BF7BC8-19C7-4DF1-8220-0688EC133324.sonar.tests=
84BF7BC8-19C7-4DF1-8220-0688EC133324.sonar.sources=\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\Controllers\\AuthController.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\Program.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\Services\\AuthService.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\Lab3.Auth.GlobalUsings.g.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\Lab3.Auth.AssemblyInfo.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\appsettings.Development.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\appsettings.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\Lab3.Auth.http",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\Properties\\launchSettings.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Lab3.Auth.csproj.nuget.dgspec.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\project.assets.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\bin\\Debug\\net10.0\\Lab3.Auth.deps.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\bin\\Debug\\net10.0\\Lab3.Auth.runtimeconfig.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\bin\\Debug\\net10.0\\Lab3.Auth.staticwebassets.endpoints.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\Lab3.Auth.sourcelink.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth\\obj\\Debug\\net10.0\\staticwebassets.build.json"

84BF7BC8-19C7-4DF1-8220-0688EC133324.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\.sonarqube\\out\\0"
84BF7BC8-19C7-4DF1-8220-0688EC133324.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\.sonarqube\\out\\0\\Issues.json"
84BF7BC8-19C7-4DF1-8220-0688EC133324.sonar.cs.scanner.telemetry=\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\.sonarqube\\out\\0\\Telemetry.json"

84BF7BC8-19C7-4DF1-8220-0688EC133324.sonar.working.directory=C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\.sonarqube\\out\\.sonar\\mod0
B90E1EE8-2314-48EA-86E9-58F26C31F620.sonar.projectKey=lab3-project:B90E1EE8-2314-48EA-86E9-58F26C31F620
B90E1EE8-2314-48EA-86E9-58F26C31F620.sonar.projectName=Lab3.Auth.Tests
B90E1EE8-2314-48EA-86E9-58F26C31F620.sonar.projectBaseDir=C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests
B90E1EE8-2314-48EA-86E9-58F26C31F620.sonar.sourceEncoding=utf-8
B90E1EE8-2314-48EA-86E9-58F26C31F620.sonar.sources=
B90E1EE8-2314-48EA-86E9-58F26C31F620.sonar.tests=\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\obj\\Lab3.Auth.Tests.csproj.nuget.dgspec.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\obj\\project.assets.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\bin\\Debug\\net10.0\\Lab3.Auth.deps.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\bin\\Debug\\net10.0\\Lab3.Auth.runtimeconfig.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\bin\\Debug\\net10.0\\Lab3.Auth.staticwebassets.endpoints.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\bin\\Debug\\net10.0\\Lab3.Auth.Tests.deps.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\bin\\Debug\\net10.0\\Lab3.Auth.Tests.runtimeconfig.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\bin\\Debug\\net10.0\\MvcTestingAppManifest.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\obj\\Debug\\net10.0\\Lab3.Auth.Tests.sourcelink.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\obj\\Debug\\net10.0\\MvcTestingAppManifest.json",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\AuthControllerTests.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\AuthServiceTests.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\UnitTest1.cs",\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\coverage-results\\08b41f98-4e72-4022-9c18-08c3e49e05ec\\coverage.cobertura.xml"

B90E1EE8-2314-48EA-86E9-58F26C31F620.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\.sonarqube\\out\\1"
B90E1EE8-2314-48EA-86E9-58F26C31F620.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\.sonarqube\\out\\1\\Issues.json"
B90E1EE8-2314-48EA-86E9-58F26C31F620.sonar.cs.scanner.telemetry=\
"C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\.sonarqube\\out\\1\\Telemetry.json"

B90E1EE8-2314-48EA-86E9-58F26C31F620.sonar.working.directory=C:\\Users\\Tujh\\Desktop\\LR3pidis\\Lab3.Auth.Tests\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=84BF7BC8-19C7-4DF1-8220-0688EC133324,B90E1EE8-2314-48EA-86E9-58F26C31F620

